  version: "3"
  services:
    mongo:
      image: mongo:latest
      container_name: "mongo-database"
      ports:
        - 27017:27017
    api:
      image: grad-practice
      ports:
        - 8080:8080
      links:
        - mongo